export const SET_SEARCH_QUERY = "SEARCH/SET_SEARCH_QUERY";
export const SET_VIDEOS = "VIDEOS/SET_VIDEOS";
export const SET_RELATED = "VIDEOS/SET_RELATED";
export const TOGGLE_IS_FETCHING_VEIDOS = "VIDEOS/TOGGLE_IS_FETCHING_VEIDOS";
